[project]
name = "datascipsych"
version = "0.1.0"
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "polars",
    "seaborn",
    "jupyterlab"
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
